name: Docker Build and Push nust1flare

on:
  push:
    branches:
      - main  # Trigger only on the 'main' branch

    paths:
      - "**"  # Trigger only if files in this path are changed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (Lite)
        uses: docker/build-push-action@v5
        with:
          context: ./
          
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nust1flare:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # build-args: |
          #   HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}